### ISSUE TITLE
Improve Trigger Build Selection Interface

### ISSUE THREAD

**Issue by MattDavisRM** [huserben/TfsExtensions#104]
I think it would be nice if there was a better entry method for selecting the build(s) to queue instead of free-form text entry.  Builds can be segregated by folders now, so it is possible to have same named definition in different folders which can cause a name conflict on which one is being queued.

**Comment by huserben** [comment]
Hi @MattDavisRM 

Thanks for your input.

I thought about that problem initially (I think it would even be possible without folders to have the same name) but I assumed that the chances that you actually have two identical names are not so high.

The only thing that I could think of would be to be able to specify the id of the build instead of the name. This is actually how the agent queue selection is implemented, either by name or by id, both work.

Would this be a proper solution for you?

**Comment by MattDavisRM** [comment]
I'm curious if the majority of consumers are triggering a single definition instead of bulk?  Or whether they'd prefer to specify a single queue just with multiple tasks each doing one?  I think listing the id list is a fine compromise, but maybe adding a single/bulk radio button and moving the current input to the bulk selection.  If only selecting a single build definition to queue, could align with how the build source selection work for the artifact source.

![image](https://user-images.githubusercontent.com/45459239/49243969-4de0e200-f3d4-11e8-9355-fc1ab9197acc.png)

**Comment by huserben** [comment]
Hi

could you elaborate what you mean by "bulk selection".
What I meant is that you could pass the id instead of the name, however it will remain a "free text" box.

Making a selection box would be possible (at least for some configurations), however it would require some configuration work on all the installed instances which I want to prevent.
There are extensions that support that, e.g. https://marketplace.visualstudio.com/items?itemName=jihedmhadhbi.TriggerNewBuild

So if the key problem is the free text box, than I'm sorry but I believe this won't change in the near future. If it's about being able to trigger builds where 2 builds have the same name, I could make the adjustment and allow id's to be entered apart from the definition name.

**Comment by huserben** [comment]
Hi @MattDavisRM 

any update on this?

**Comment by huserben** [comment]
Closed due to inactivity.
Please reopen in case additional functionality or investigation is needed.
