### ISSUE TITLE
Trigger new build add "C" to changesetversion

### ISSUE THREAD

**Issue by DDeAlmeida** [huserben/TfsExtensions#111]
Hi, 
I'm using your extension, all are work as espected except when i trigger a new build with "Use current changeset for the triggered build" option.

The trigger build have the same changeset but prefixed by "C".

Build 1 : ( which trigger build 2 )
Get sources : ##[command]tf vc get /version:943 /recursive ....
Trigger a new build : Triggered Build will use the same source version: C943

Build 2 :
Get sources :  ##[command]tf vc get /version:C943

How can i have the version without prefixed "C" ?

My Nuget Restore crash du to this "C" because the letter is not expected...
System.ArgumentException: '10.2.55.C943-Dev' is not a valid version string.

Thank you

My TFS : 15.117.27414.0 => 2017.3.1

**Comment by huserben** [comment]
Hi @DDeAlmeida 

Thanks for your feedback.
As far as I remember is the "C" prefix needed when we specify the exact version on a TFVC environment.
However it feels odd if the nuget fails due to that.

Could you once try to queue "Build 2" manually and specify the source version explicitly:
![grafik](https://user-images.githubusercontent.com/5486874/60398925-fb2ffa00-9b5d-11e9-8403-b899336ce693.png)

If you have the same problem with this, then it seems to be an Issue with TFS or the nuget restore.
In case you have some custom script or so to invoke the restore that relies on the source version variable you might be able to just "ignore" prepended "C"s (or "L" in case someone builds for a specific label).

**Comment by DDeAlmeida** [comment]
Hi, thank you for your answer.
Same error when build 2 is launch with "C" + Changeset Number

I added a powershell to remove the C when is present in Build.BUILD_SOURCEVERSION

Thank you
