### ISSUE TITLE
How to access build parameters in other build jobs

### ISSUE THREAD

**Issue by henrikstromberg** [huserben/TfsExtensions#134]
I have a Trigger buildtask in one project with the build paramerter    buildParameters: "ServiceName: sample-service"

How do I access in in my other build pipeline as a parameter to a powershell script or directly in the poweshell script?

this is not documented https://github.com/huserben/TfsExtensions/blob/master/BuildTasks/overview.md#build-parameters

I also tried to use this in the other buildpipline but no value vas set
Write-Output "Fetching variable TriggeredBuildIds:"
Write-Output "$($env:TriggeredBuildIds)"

**Comment by huserben** [comment]
Hi @henrikstromberg 

When you pass a variable you will need to define this variable in the build that is triggered and specify it to be settable at queue time.
So that means if you have two builds:
- Build A
- Build B

Your _Build A_ is triggering _Build B_ with the mentioned configuration of _ServiceName: sample-service_.
In _Build B_ you then must have defined a variable called _ServiceName_ that has the _Settable at Queue Time_ box ticked. In _Build B_ you then can access this like any other variable:
- In Powershell script via _$env:ServiceName_
- As input to tasks via $(ServiceName)

The TriggeredBuildIds variable is set when you specify the check box in the settings under _Stored Environment Variable_. It is then available in the build that is triggering (_Build A_ in our example).

Did this clarify a bit the usage of the variables?

**Comment by henrikstromberg** [comment]
Thanks for the help it solved my problem :-)
