### ISSUE TITLE
No valid OAuth token provided. Please check that you have the OAuth Token Access allowed for your builds.

### ISSUE THREAD

**Issue by tophallen** [huserben/TfsExtensions#166]
We started getting this error for every build trigger around the time the most recent (3.1.0) update was pushed out.

We have OAuth token enabled for the agent/job, and we left the access token blank so that it would try to get `System.AccessToken`. It's a little tough to tell from the PRs - but it does seem like the most recent change changes how that token is being retrieved.

Best I can see is the only change happened [here](BuildTasks/cancelbuildtask/cancelbuildtaskV2/taskrunner.ts) in #139

We are using Azure DevOps Services and our agents are running 2.157.2 on Windows Server.

Seems like it might make sense to fall back on the old method of getting the access token, and then fail after that.

**Comment by mwisebaker** [comment]
I'm getting the same issue under the same conditions. Was already using OAuth token and worked fine under 2.* version of the task. Just started getting this error under 3.*. Changed back to 2 and everything worked as expected.

**Comment by huserben** [comment]
Hmm seems like this change might have broken this, somehow slipped through my testing. I'll try to revert this and push a fix asap.

**Comment by tophallen** [comment]
Awesome, thanks! Honestly not sure why that change doesn't work - I feel like it should based on the MS documentation...

**Comment by mwisebaker** [comment]
Thanks!

I deleted my comment because it turns out that it broke under 2.* too with a slightly different error: Authentication with TFS Server failed. Please check your settings.

Have it working with a PAT now but I’ll keep my eye open.

Michael D. Wisebaker
Senior Software Engineer
REC Technology
Mailcode: KS-01-11-0501
Phone: 913/317-4566

"If it's not unit tested, it's broken."
Pragmatic Programming Tips<https://pragprog.com/tips/>
[cid:image001.png@01D70F77.FDA3BC10]

**Comment by huserben** [comment]
@tophallen 

As a workaround, you can pass $(System.AccessToken) as a password when selecting OAuth.

**Comment by tophallen** [comment]
Yeah, that's what we are doing for now. Thanks.

**Comment by huserben** [comment]
#167  should have fixed it, it seems the new verison of the task lib imported the values now as undefined instead of null/"".
Thus it didn't try to fetch the token in the first place.

A new version is published now, please let me know whether it helped. If not I fear you'll have to use the workaround till tomorrow as it's getting late here.

Sorry for the troubles I've created.

**Comment by huserben** [comment]
I updated my test builds now to not specify anything, updated the task to the last published versions and it works.

![image](https://user-images.githubusercontent.com/5486874/109722896-a273f880-7bad-11eb-9bec-a726d6280450.png)

If it works for you as well @tophallen feel free to close the issue.

Thanks for making me aware so quickly, I think due to that you saved a lot of other people some trouble (as Europe is asleep now :-)).
Sorry once more for the trouble I've caused, I hope it didn't derail your plans for today too much.

**Comment by tophallen** [comment]
I'll test it now and close if it is fixed - at least there is a work around. Thanks for working so quickly on this @huserben.

**Comment by mwisebaker** [comment]
That seems to have fixed it for my build.

[cid:image001.png@01D70F80.9ACA51E0]

Michael D. Wisebaker
Senior Software Engineer
REC Technology
Mailcode: KS-01-11-0501
Phone: 913/317-4566

"If it's not unit tested, it's broken."
Pragmatic Programming Tips<https://pragprog.com/tips/>
[cid:image004.png@01D70F80.9DED63D0]

**Comment by tophallen** [comment]
Confirmed this has been fixed. Thanks for the quick work! Closing this issue.
