### ISSUE TITLE
Creating a main Gated check-in enabled build definition and using a single source for all triggered builds.

### ISSUE THREAD

**Issue by LesCodeables** [huserben/TfsExtensions#19]
We have multiple CI build definitions which I want to trigger from one main Build definition to enable gated check-in. I want to know, will it get the changeset in the child builds and build the solution or it will get the latest source in the child builds?

**Comment by huserben** [comment]
Hi

by default it will use the newest version.
However under advanced properties you will find the option "Use Same Source Version" which, when activated, will trigger the builds for the same source version as the original build

**Comment by LesCodeables** [comment]
Hi,
In case of gated check-ins the changeset is shelved and built. If the build fails then the checkin is denied. I know that by default it gets the latest version, I want to know whether it will pick the shelveset for child builds.

**Comment by huserben** [comment]
Hi

yes, as said, if you tick these 2 options under Advanced Configuration:
![shelveset](https://user-images.githubusercontent.com/5486874/28522862-03cef80c-707a-11e7-9e79-21cf6e192770.PNG)

it will run the triggered builds for the shelveset:
![triggeredbuild](https://user-images.githubusercontent.com/5486874/28522898-3b1dbf64-707a-11e7-88d6-24be7ea6e232.PNG)

And the triggered build will then use the same sources:
![build](https://user-images.githubusercontent.com/5486874/28522936-6770a8c4-707a-11e7-804b-6ce597a298f9.PNG)

This should support your gated check-in use case.

However as far as I understand the gated-checkin process it will check whether the triggered build will be successful. This means you need to wait for the triggered builds to finish and in case they fail as well fail your gated check-in build. In order to wait for builds to finish you need at least 2 build agents, as otherwise you will end up in a deadlock situation as the triggered build will wait for the other builds to finish but those cannot be started as long as one build is running...

**Comment by LesCodeables** [comment]
Hi,
Thanks for the reply. I understand what you are saying. as yous said, I have been using two different build agents, one for main build and other for triggered builds. The problem here is, my triggered builds have a Get Sources build task. Now, if the builds are going to be on different agents, how are they going to share the same source as they will have different workspaces? I'm in bit of a confusion there.

**Comment by huserben** [comment]
Hi
the GetSources task will use the same shelveset when you specify those two options I mentioned above. So when we trigger the the build we will pass parameters that define which source version to use, so it doesn't matter on which agent you run it.

**Comment by huserben** [comment]
Hi @LesCodeables 

were you able to solve your problem or do you need further assistance?

**Comment by huserben** [comment]
Due to inactivity I will close the issue

**Comment by LesCodeables** [comment]
I'm apologise for not responding. I was out for a while.  I would like to know whether is it possible to use the same workspace for both parent and child build?

**Comment by huserben** [comment]
Hi @LesCodeables 

what exactly do you mean by same workspace? The same source version or something else?

**Comment by LesCodeables** [comment]
Hi,
By workspace I mean the same location of files on the agent. Now, I'm triggering a build definition from another build definition and I want the two definitions to use the exact same workspace on the agent. Is that possible. I'm not talking about the source version here.

**Comment by huserben** [comment]
Hi

ok I don't think this is possible, at least i never saw some setting for this.
As well the workspace is depending on the build agent, so if the build would be triggered on another agent this cannot work.

I'm not entierly sure but I think TFS will create another mapped folder for every build definition, so I think technically it cannot use the same workspace for builds of different definitions.
