### ISSUE TITLE
Trigger build with same definition name but different folder

### ISSUE THREAD

**Issue by Dimigergo** [huserben/TfsExtensions#224]
Hello!

I have a build definition whitch use this extension to start a build definition. The problem is that I use two build definition with the same name but different folder. The Trigger Build extension always starts the release2 folder MLR.MoLaRi.HQ.HQService build. Can I use somehow the folder to point the exact build definition? I cannot use the branchname for this, because the two build definition absolutely different tasks, but use common task groups which use (Build.DefinitionName) variable inside (f.e.: the project name and the folder is that name). Thats why the two build definition name is the same. We have 128 projects with installers, so basycally more than 200 build definition, so I prefer to use the $(Build.DefinitionName) variable in it instead of rename the build definition to unique.

So the simpliest solution for me if I can specify the folder of the build definition. F.e.: release4/MLR.MoLaRi.HQ.HQService

![2022_10_10_11_05_07_MoLaRi_Release_release4_Azure_DevOps_Server](https://user-images.githubusercontent.com/11498949/194832452-d079d6b1-dab7-448f-81ab-9e04f3c79a94.png)

![2022_10_10_10_50_51_Pipelines_All](https://user-images.githubusercontent.com/11498949/194832506-332d2928-2c85-42dc-bbe4-5c1adadfea8c.png)

Thanks in advance!

**Comment by huserben** [comment]
Hi @Dimigergo 

thanks for raising your question.
I'm not sure how the folder name is returned from the API, thus it would require some investment and adjustment of the task (which currently is not realistic from my side as I don't have much time).

I see your problem though and there might be another way. It's not as "nice" to read it, but you could specify the Definition ID instead of the name. In order to increase readability you could also add a variable that maps the definition name to the actual ID.

You can find the ID by opening the respective build definition and see what "number" is in the URL:
![Definition ID](https://user-images.githubusercontent.com/5486874/194875072-f944b487-83f3-41f1-aa8a-61aef2360d5e.png)


Please let me know if this would be a viable option for you.

**Comment by Dimigergo** [comment]
Thanks for the response!
Tomorrow, I will try, your suggestion absolutely good for us. I saw that can enter the name or the ID, but didn`t know where can I find the ID. :)

So thanks, tomorrow will let you know if it works.

**Comment by huserben** [comment]
Yes please let me know, if not I'm happy to support.

**Comment by Dimigergo** [comment]
It's perfect, thank you for your suggestion!
