### ISSUE TITLE
Build failing when template parameters passed but not when template parameters are not passed

### ISSUE THREAD

**Issue by philgitphoton** [huserben/TfsExtensions#256]
First, thanks for this extension, its great!

I have written many build triggers with your add on and they work fine. But lately, something has changed in my AZDO project config I feel (its not a bug with your addon)

Inside my own project, when using the build trigger and passing template parameters I receive:
"Could not queue the build because their were validation errors or warnings"

If I remove the template parameters line entirely, the triggerbuild script runs fine using some defaults I have set

My existing build triggers are running no problem at all, the problem is only with new build triggers I am creating

The newly created build triggers that have the issue are within the same project as the builds they call

If I try the newly created build trigger within a different project (same org) it will work fine, with or without params

I have queue builds permission set (and when it isn't I can see there is a specific error message for that) 

It can only be something different/changed in my project settings - I wondered if you had experienced this or may know where to look perhaps?  I am reluctant to start comparing permissions with the other projects right now in case I knock out the existing build triggers. changing things.

I think the error message I am getting is a red herring in this case perhaps?

thanks a mill.

**Comment by huserben** [comment]
Hi @philgitphoton 

thanks for raising this issue. It does sound very strange to me, I would not know why different permissions would be needed to trigger a pipeline with template parameters than without them (but one can never know).

Regarding the error message: it's what we get from the API from ADO, so we don't know more...
Often this error comes when we send some invalid message, like we have an invalid json. But given that you have used the template parameters before and they work, I don't think that's it. I assume there is nothing "special" about those template parameters compared to the others you are using?

Or is there anything else you can see that is different in your new pipelines?
- Are the ones that that use the task new pipelines or where they existing before already?
- Are the triggered pipelines new or where they existing before?

Sorry for the generic questions, but as I don't see any lead so far, I think it's the only way to try to find some root cause.
