### ISSUE TITLE
Version 2 TiggerBuildTask Setting TriggeredBuildIds Environment Variable Differently Than Version 1

### ISSUE THREAD

**Issue by toddbrownmcis** [huserben/TfsExtensions#29]
Version 2 TfsExtensions/BuildTasks/triggerbuildtask/index.js is setting **TriggeredBuildIds** environment variable to comma delimited string of **previous value** + **newly triggered builds**.

Version 1 TfsExtensions/BuildTasks/powershellTask/triggerbuildtask/triggerbuild.ps1 is setting **TriggeredBuildIds** environment variable to comma delimited string of **newly tiggered builds**.

I think Version 1 is doing it correctly since the previous value used in Version 2 is from the last time any Trigger Build task was run which may be several days ago and has nothing to do with the current task.

**Comment by huserben** [comment]
Hi @toddbrownmcis 

hmm the variable in the new version actually only "lives" while the build is run, after this it should be emptied directly. The reason why the previous values are stored is if you want to trigger more than one build with different conditions (meaning you need 2 differently configured tasks) and await both of them later with the separate wait task.

So the value set in the variable should nto be anymore after the build finished.

Do you have a concrete issue or experienced a different behavior?

**Comment by toddbrownmcis** [comment]
I am switching from version 1 to version 2.  So the user environment variable has a value set from the last version 1 task.  It seems that the version 2 task is always starting with a previous value from the last version 1 task and appending the current version 2 task.

**Comment by huserben** [comment]
Hi

oh that makes sense, as PowerShell actually used a "persistent" variable. However the task will not be able to delete this value, because as far as I know this is not possible using node.js.
However you could try to "clean" the environment variable before with a little powershell script/snippet and from then on it should be fine.

Could you test it with adding a Powershell script that executes this:
[Environment]::SetEnvironmentVariable("TriggeredBuildIds", ",", "User")

It should be enough to just run this once to reset the variable.

**Comment by huserben** [comment]
Hi @toddbrownmcis 

did you have the chance to look into it and run the PowerShell script to clear the variable?

Thanks for your feedback

**Comment by toddbrownmcis** [comment]
Yes, that fixed the issue. Thanks!

**Comment by huserben** [comment]
Hi

ok very good. I will leave the issue open until I documented the this as well on the overview page.
