### ISSUE TITLE
Performance Query

### ISSUE THREAD

**Issue by ConnMckay** [huserben/TfsExtensions#36]
Hello Benj,
I have been looking for a plugin to TFS to chain Build Definitions and yours looks like it fits the bill.

With any extension/plug-in we have to allow for a certain amount of depreciation in Performance and  I will wondering to what extent with your tool ?  On the face if I would think it is negligible, but this is a question coming from our DevOps before they will give the go-ahead to install.

Thanks in advance

**Comment by huserben** [comment]
Hi @ConnMckay 

so just to confirm if I get the question correct. You're wondering about the performance impact of having the Task installed for your TFS server and/or running the single build definitions?

I don't think there is any performance impact, basically the task is nothing else than a packaged node.js script that is run on the build agents. No service/program needs to be additionally installed, it will only take a few megabytes of each your build agents.

I hope that answers your question, otherwise let me know if I need to clarify something else or in more detail :-)

**Comment by ConnMckay** [comment]
Hi Benj,
That certainly does. Thanks for getting back to me and also for the tool.

Sent from my Windows 10 phone

________________________________
