### ISSUE TITLE
Small documentation bug on build parameters

### ISSUE THREAD

**Issue by cgnuechtel** [huserben/TfsExtensions#45]
Hi Benj,

thanks for this great plugin 👍

I think there is small documentation bug on https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks regarding build parameters.

The documentation says:

> All variable names and values must be enclosed by a "
"VariableIWantToSet" : "WhateverValue"

But, at least on TFS 2018 it must be:

`\"VariableIWantToSet\":\"WhateverValue\"`

It cost me at least one hour to find that out 🙈
But now, everything works and I am absolutely happy with your plugin ☺️

Bye for now
Christian

**Comment by huserben** [comment]
Hi @cgnuechtel 

I'm sorry that you wasted an hour due to that issue.
Thanks for reporting this and potential save others this hour where they have to figure that out.

The thing is, I'm pretty certain this (once) was correct, at least locally when looking at the md file it looks fine (using MarkdownPad 2):
![grafik](https://user-images.githubusercontent.com/5486874/35409065-76d7c53a-0211-11e8-99d8-b97109079949.png)
![grafik](https://user-images.githubusercontent.com/5486874/35409080-7f49e0c2-0211-11e8-9301-e93ef94bb003.png)

However I think it could be that due to a change of the markdown-parser on the marketplace this somehow got changed.
I'll need to figure out more and then I can hopfeully soon make the appropriate changes so it displays in the documentation what it should.

I will leave the issue open until this has happened.

**Comment by huserben** [comment]
HI @cgnuechtel 

In the newest version this issue is fixed and it's now properly displayed in the overview page.

Thanks again for your feedback.

**Comment by cgnuechtel** [comment]
Thank you very much.
The time I spent is minimal. No problem at all.
It is a great pleasure to use your plugin.
