### ISSUE TITLE
Trigger a buil d with a different branch wont work

### ISSUE THREAD

**Issue by hacknslay** [huserben/TfsExtensions#79]
First of all, thanks for your contribution. I know that this cost a lot of hours.

My goal was to develop a build definition, that i can trigger with another build definition. With this configuration i should be able to call these definitions with custom source branches.

Without triggering, i have to define a definition for each branch, that is not my favorite.

I have following situation:

Source is stored in TFVC-Repository. TFS 2018 Update 2 On-Premise

Builds:
+ Component_1
   - has a mapping to $/Company/Product/Main
+ Component_2
   - has a mapping to $/Company/Product/Main
+ AllProducts_Feature1
   - will trigger Build "Component_1" with branch "$/Company/Product/Feature1
   - will trigger Build "Component_2" with branch "$/Company/Product/Feature1
+ AllProducts_Release_1.42
   - will trigger Build "Component_1" with branch "$/Company/Product/Release/1.42
   - will trigger Build "Component_2" with branch "$/Company/Product/Release/1.42

This will not work, because the source branch will not be overgiven to the trigger builds.

![grafik](https://user-images.githubusercontent.com/18185942/41853396-f8e4afaa-788d-11e8-966c-fd77b68d7290.png)

![grafik](https://user-images.githubusercontent.com/18185942/41853500-343b24d0-788e-11e8-9c0e-181eeeea3d22.png)

Do i have missed something to configure or is this only possible with a git-repo?

Greetings

**Comment by huserben** [comment]
Hi @hacknslay 

unfortunately I think it's not possible what you try to achieve. The problem is that TFVC actually has a different path for different branches, while with git the structure stays the same and it will just "switch" the branch. This makes it way easier to have build definitions for different branches.
So in case you have the possibility to switch to git i would recommend it - however I know from experience that this is not easily possible :-)

So there is no way around having multiple build definitions, because to my knowledge the "GetSources" step cannot be parametrized.
So given the following structure:

- MyTfsRepo
 -- MainBranch
  --- MySolutionDirectory
 -- MyFeatureBranch
  --- MySolutionDirectory

We have to either map the whole repo and the we would have different paths to the actual solution to build. Or we just map the "Branch Root Folder", which makes the path to the solution "relative", but then we somehow need to decide which sources to get.
Actually this was once possible, but the functionality was removed: https://blogs.msdn.microsoft.com/tfssetup/2016/08/01/vnext-build-using-a-variable-for-server-path-for-repository-is-not-supported/

Anyway what we do in my company to circumvent this problem is making use of TaskGroups. You could put your complete build (with all the tasks) into one task group. Then you define a variable which is something like "$(Branch)" that you use within the task group. This should be the path to you mapped root directory, for example either "$/MyTfsRepo/MainBranch" or "$/MyTfsRepo/MyFeatureBranch".
Now you would still need two builds, one per branch, in which you setup the GetSources step with the corresponding path, but then you could invoke the TaskGroup which contains the shared steps with the Path you want.
It's not ideal, but at least you don't have too much copy-paste of the build tasks.

I think my Trigger Task won't help you here though.
Anyway let me know whether my explanation was of any help, or if I did get the question completly wrong.

**Comment by hacknslay** [comment]
Hi @huserben,

thank you very much for your detailed answer.

I think you are right, with the tfvc-repo i cannot do this and the link to the msdn-blog clarify this. Ok, just in the moment i feel a little bit left out in the rain by microsoft - and i was very excited about the new build system (i try to migrate our xaml-buildprocesses to vNext).

Anyway, the best solution here in my opinion is your approach with a build definition that "shares" the other build tasks in task groups. With TFS 2018.2 i have there much better options as before in 2017.2 wich was a pain.

Thank you very much for your solution and have great day!
